# Generated by Django 4.2 on 2023-04-18 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=500)),
                ('last_update', models.DateTimeField()),
                ('logo', models.ImageField(upload_to='')),
                ('transaction_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=16)),
                ('date_time', models.DateTimeField()),
                ('currency_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curency_from', to='convert.currency')),
                ('currency_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curency_to', to='convert.currency')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convert.provider')),
            ],
        ),
    ]
